name: TavernSwitcher
options:
  bundleIdPrefix: top.sillytavern
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: top.sillytavern.tavernswitcher
    MARKETING_VERSION: "4.1"
    CURRENT_PROJECT_VERSION: "32"
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"
targets:
  TavernSwitcher:
    type: application
    platform: iOS
    sources:
      - path: TavernSwitcher
    settings:
      base:
        INFOPLIST_FILE: TavernSwitcher/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: false
    scheme:
      testTargets: []
